// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	GetInterestRequest
	GetInterestResponse
	GetEntriesRequest
	GetEntriesResponse
	ApproveEntriesRequest
	ApproveEntriesResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetInterestRequest struct {
	AuthToken string `protobuf:"bytes,1,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
}

func (m *GetInterestRequest) Reset()                    { *m = GetInterestRequest{} }
func (m *GetInterestRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInterestRequest) ProtoMessage()               {}
func (*GetInterestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetInterestRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type GetInterestResponse struct {
	Success    bool                            `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message    string                          `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Title      string                          `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Body       string                          `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	Categories []*GetInterestResponse_Category `protobuf:"bytes,5,rep,name=categories" json:"categories,omitempty"`
}

func (m *GetInterestResponse) Reset()                    { *m = GetInterestResponse{} }
func (m *GetInterestResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInterestResponse) ProtoMessage()               {}
func (*GetInterestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetInterestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetInterestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetInterestResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetInterestResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetInterestResponse) GetCategories() []*GetInterestResponse_Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type GetInterestResponse_Category struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	WeightRange string `protobuf:"bytes,3,opt,name=weight_range,json=weightRange" json:"weight_range,omitempty"`
	Parent      int32  `protobuf:"varint,4,opt,name=parent" json:"parent,omitempty"`
	Level       int32  `protobuf:"varint,5,opt,name=level" json:"level,omitempty"`
}

func (m *GetInterestResponse_Category) Reset()                    { *m = GetInterestResponse_Category{} }
func (m *GetInterestResponse_Category) String() string            { return proto.CompactTextString(m) }
func (*GetInterestResponse_Category) ProtoMessage()               {}
func (*GetInterestResponse_Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *GetInterestResponse_Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetInterestResponse_Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInterestResponse_Category) GetWeightRange() string {
	if m != nil {
		return m.WeightRange
	}
	return ""
}

func (m *GetInterestResponse_Category) GetParent() int32 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *GetInterestResponse_Category) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type GetEntriesRequest struct {
	AuthToken string `protobuf:"bytes,1,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
}

func (m *GetEntriesRequest) Reset()                    { *m = GetEntriesRequest{} }
func (m *GetEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesRequest) ProtoMessage()               {}
func (*GetEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetEntriesRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type GetEntriesResponse struct {
	Success    bool                           `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message    string                         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Categories []*GetEntriesResponse_Category `protobuf:"bytes,3,rep,name=categories" json:"categories,omitempty"`
	Questions  []*GetEntriesResponse_Question `protobuf:"bytes,4,rep,name=questions" json:"questions,omitempty"`
}

func (m *GetEntriesResponse) Reset()                    { *m = GetEntriesResponse{} }
func (m *GetEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse) ProtoMessage()               {}
func (*GetEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetEntriesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetEntriesResponse) GetCategories() []*GetEntriesResponse_Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *GetEntriesResponse) GetQuestions() []*GetEntriesResponse_Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type GetEntriesResponse_Category struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	WeightRange string `protobuf:"bytes,3,opt,name=weight_range,json=weightRange" json:"weight_range,omitempty"`
	Parent      int32  `protobuf:"varint,4,opt,name=parent" json:"parent,omitempty"`
	Level       int32  `protobuf:"varint,5,opt,name=level" json:"level,omitempty"`
}

func (m *GetEntriesResponse_Category) Reset()                    { *m = GetEntriesResponse_Category{} }
func (m *GetEntriesResponse_Category) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse_Category) ProtoMessage()               {}
func (*GetEntriesResponse_Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *GetEntriesResponse_Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetEntriesResponse_Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEntriesResponse_Category) GetWeightRange() string {
	if m != nil {
		return m.WeightRange
	}
	return ""
}

func (m *GetEntriesResponse_Category) GetParent() int32 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *GetEntriesResponse_Category) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type GetEntriesResponse_Question struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *GetEntriesResponse_Question) Reset()                    { *m = GetEntriesResponse_Question{} }
func (m *GetEntriesResponse_Question) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse_Question) ProtoMessage()               {}
func (*GetEntriesResponse_Question) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 1} }

func (m *GetEntriesResponse_Question) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetEntriesResponse_Question) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetEntriesResponse_Question) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GetEntriesResponse_Question_Answer struct {
	Option1 string `protobuf:"bytes,1,opt,name=option1" json:"option1,omitempty"`
	Option2 string `protobuf:"bytes,2,opt,name=option2" json:"option2,omitempty"`
	Option3 string `protobuf:"bytes,3,opt,name=option3" json:"option3,omitempty"`
	Option4 string `protobuf:"bytes,4,opt,name=option4" json:"option4,omitempty"`
	Option5 string `protobuf:"bytes,5,opt,name=option5" json:"option5,omitempty"`
}

func (m *GetEntriesResponse_Question_Answer) Reset()         { *m = GetEntriesResponse_Question_Answer{} }
func (m *GetEntriesResponse_Question_Answer) String() string { return proto.CompactTextString(m) }
func (*GetEntriesResponse_Question_Answer) ProtoMessage()    {}
func (*GetEntriesResponse_Question_Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 1, 0}
}

func (m *GetEntriesResponse_Question_Answer) GetOption1() string {
	if m != nil {
		return m.Option1
	}
	return ""
}

func (m *GetEntriesResponse_Question_Answer) GetOption2() string {
	if m != nil {
		return m.Option2
	}
	return ""
}

func (m *GetEntriesResponse_Question_Answer) GetOption3() string {
	if m != nil {
		return m.Option3
	}
	return ""
}

func (m *GetEntriesResponse_Question_Answer) GetOption4() string {
	if m != nil {
		return m.Option4
	}
	return ""
}

func (m *GetEntriesResponse_Question_Answer) GetOption5() string {
	if m != nil {
		return m.Option5
	}
	return ""
}

type ApproveEntriesRequest struct {
	AuthToken  string                            `protobuf:"bytes,1,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	Categories []*ApproveEntriesRequest_Category `protobuf:"bytes,3,rep,name=categories" json:"categories,omitempty"`
	Questions  []*ApproveEntriesRequest_Question `protobuf:"bytes,4,rep,name=questions" json:"questions,omitempty"`
}

func (m *ApproveEntriesRequest) Reset()                    { *m = ApproveEntriesRequest{} }
func (m *ApproveEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*ApproveEntriesRequest) ProtoMessage()               {}
func (*ApproveEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApproveEntriesRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *ApproveEntriesRequest) GetCategories() []*ApproveEntriesRequest_Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ApproveEntriesRequest) GetQuestions() []*ApproveEntriesRequest_Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type ApproveEntriesRequest_Category struct {
	Id       int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Approved bool  `protobuf:"varint,2,opt,name=approved" json:"approved,omitempty"`
}

func (m *ApproveEntriesRequest_Category) Reset()         { *m = ApproveEntriesRequest_Category{} }
func (m *ApproveEntriesRequest_Category) String() string { return proto.CompactTextString(m) }
func (*ApproveEntriesRequest_Category) ProtoMessage()    {}
func (*ApproveEntriesRequest_Category) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *ApproveEntriesRequest_Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApproveEntriesRequest_Category) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

type ApproveEntriesRequest_Question struct {
	Id       int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Approved bool  `protobuf:"varint,2,opt,name=approved" json:"approved,omitempty"`
}

func (m *ApproveEntriesRequest_Question) Reset()         { *m = ApproveEntriesRequest_Question{} }
func (m *ApproveEntriesRequest_Question) String() string { return proto.CompactTextString(m) }
func (*ApproveEntriesRequest_Question) ProtoMessage()    {}
func (*ApproveEntriesRequest_Question) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 1}
}

func (m *ApproveEntriesRequest_Question) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApproveEntriesRequest_Question) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

type ApproveEntriesResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ApproveEntriesResponse) Reset()                    { *m = ApproveEntriesResponse{} }
func (m *ApproveEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*ApproveEntriesResponse) ProtoMessage()               {}
func (*ApproveEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApproveEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApproveEntriesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInterestRequest)(nil), "user.GetInterestRequest")
	proto.RegisterType((*GetInterestResponse)(nil), "user.GetInterestResponse")
	proto.RegisterType((*GetInterestResponse_Category)(nil), "user.GetInterestResponse.Category")
	proto.RegisterType((*GetEntriesRequest)(nil), "user.GetEntriesRequest")
	proto.RegisterType((*GetEntriesResponse)(nil), "user.GetEntriesResponse")
	proto.RegisterType((*GetEntriesResponse_Category)(nil), "user.GetEntriesResponse.Category")
	proto.RegisterType((*GetEntriesResponse_Question)(nil), "user.GetEntriesResponse.Question")
	proto.RegisterType((*GetEntriesResponse_Question_Answer)(nil), "user.GetEntriesResponse.Question.Answer")
	proto.RegisterType((*ApproveEntriesRequest)(nil), "user.ApproveEntriesRequest")
	proto.RegisterType((*ApproveEntriesRequest_Category)(nil), "user.ApproveEntriesRequest.Category")
	proto.RegisterType((*ApproveEntriesRequest_Question)(nil), "user.ApproveEntriesRequest.Question")
	proto.RegisterType((*ApproveEntriesResponse)(nil), "user.ApproveEntriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	// Respond on login
	GetInterests(ctx context.Context, in *GetInterestRequest, opts ...grpc.CallOption) (*GetInterestResponse, error)
	// Admins can view entries
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	// Admins can approve entries
	ApproveEntries(ctx context.Context, in *ApproveEntriesRequest, opts ...grpc.CallOption) (*ApproveEntriesResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetInterests(ctx context.Context, in *GetInterestRequest, opts ...grpc.CallOption) (*GetInterestResponse, error) {
	out := new(GetInterestResponse)
	err := grpc.Invoke(ctx, "/user.User/GetInterests", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	out := new(GetEntriesResponse)
	err := grpc.Invoke(ctx, "/user.User/GetEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ApproveEntries(ctx context.Context, in *ApproveEntriesRequest, opts ...grpc.CallOption) (*ApproveEntriesResponse, error) {
	out := new(ApproveEntriesResponse)
	err := grpc.Invoke(ctx, "/user.User/ApproveEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	// Respond on login
	GetInterests(context.Context, *GetInterestRequest) (*GetInterestResponse, error)
	// Admins can view entries
	GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error)
	// Admins can approve entries
	ApproveEntries(context.Context, *ApproveEntriesRequest) (*ApproveEntriesResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetInterests(ctx, req.(*GetInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetEntries(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ApproveEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ApproveEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/ApproveEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ApproveEntries(ctx, req.(*ApproveEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterests",
			Handler:    _User_GetInterests_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _User_GetEntries_Handler,
		},
		{
			MethodName: "ApproveEntries",
			Handler:    _User_ApproveEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xae, 0x1d, 0x3b, 0x3f, 0x67, 0x5a, 0x55, 0xfa, 0x0d, 0x50, 0x16, 0x03, 0x52, 0x6b, 0x71,
	0xe8, 0x29, 0x12, 0x09, 0xe5, 0x8a, 0x52, 0xa8, 0x2a, 0x24, 0x38, 0x60, 0xc1, 0xb9, 0x72, 0x93,
	0x51, 0x6a, 0x91, 0x7a, 0xcd, 0xee, 0xa6, 0x55, 0x4f, 0xdc, 0x79, 0x0b, 0xde, 0x80, 0x23, 0xaf,
	0xc1, 0x13, 0xf0, 0x2a, 0x68, 0xd7, 0x5e, 0xbb, 0x69, 0x36, 0xe1, 0xdf, 0x81, 0xdb, 0x7e, 0x33,
	0x9e, 0xd9, 0x6f, 0x66, 0xbe, 0x59, 0x03, 0xcc, 0x25, 0x89, 0x7e, 0x29, 0xb8, 0xe2, 0x18, 0xe8,
	0x73, 0x32, 0x04, 0x3c, 0x26, 0xf5, 0xb2, 0x50, 0x24, 0x48, 0xaa, 0x94, 0x3e, 0xcc, 0x49, 0x2a,
	0x7c, 0x08, 0x90, 0xcd, 0xd5, 0xd9, 0x89, 0xe2, 0xef, 0xa9, 0x60, 0xde, 0xae, 0xb7, 0xdf, 0x4b,
	0x7b, 0xda, 0xf2, 0x56, 0x1b, 0x92, 0xaf, 0x3e, 0xdc, 0x5a, 0x88, 0x92, 0x25, 0x2f, 0x24, 0x21,
	0x83, 0xff, 0xe4, 0x7c, 0x3c, 0x26, 0x29, 0x4d, 0x4c, 0x94, 0x5a, 0xa8, 0x3d, 0xe7, 0x24, 0x65,
	0x36, 0x25, 0xe6, 0x9b, 0x6c, 0x16, 0xe2, 0x6d, 0x08, 0x55, 0xae, 0x66, 0xc4, 0x3a, 0xc6, 0x5e,
	0x01, 0x44, 0x08, 0x4e, 0xf9, 0xe4, 0x8a, 0x05, 0xc6, 0x68, 0xce, 0x78, 0x08, 0x30, 0xce, 0x14,
	0x4d, 0xb9, 0xc8, 0x49, 0xb2, 0x70, 0xb7, 0xb3, 0xbf, 0x39, 0x48, 0xfa, 0xa6, 0x22, 0x07, 0x99,
	0xfe, 0xf3, 0xea, 0xdb, 0xab, 0xf4, 0x5a, 0x54, 0xfc, 0x11, 0x22, 0x6b, 0xc7, 0x6d, 0xf0, 0xf3,
	0x89, 0x21, 0x1a, 0xa6, 0x7e, 0x3e, 0xd1, 0x77, 0x16, 0xd9, 0xb9, 0x25, 0x68, 0xce, 0xb8, 0x07,
	0x5b, 0x97, 0x94, 0x4f, 0xcf, 0xd4, 0x89, 0xc8, 0x8a, 0xa9, 0x25, 0xb9, 0x59, 0xd9, 0x52, 0x6d,
	0xc2, 0x1d, 0xe8, 0x96, 0x99, 0xa0, 0x42, 0x19, 0xb2, 0x61, 0x5a, 0x23, 0x5d, 0xd8, 0x8c, 0x2e,
	0x68, 0xc6, 0x42, 0x63, 0xae, 0x40, 0x32, 0x80, 0xff, 0x8f, 0x49, 0x1d, 0x15, 0x4a, 0xd3, 0xf9,
	0xc5, 0x76, 0x7f, 0x0e, 0xcc, 0x90, 0x9a, 0xa0, 0xbf, 0xe8, 0xf6, 0x68, 0xa1, 0x87, 0x1d, 0xd3,
	0xc3, 0xbd, 0xa6, 0x87, 0x37, 0x6e, 0x70, 0xb6, 0x10, 0x9f, 0x41, 0xcf, 0xb0, 0xce, 0x79, 0x21,
	0x59, 0xf0, 0x93, 0x0c, 0x6f, 0xea, 0x2f, 0xd3, 0x36, 0xe6, 0x9f, 0xcf, 0x20, 0xfe, 0xe6, 0x41,
	0x64, 0x89, 0x2d, 0x31, 0x68, 0xf4, 0xe8, 0xbb, 0xf4, 0xd8, 0x69, 0xf5, 0x18, 0x7f, 0xf2, 0xa0,
	0x3b, 0x2a, 0xe4, 0x25, 0x09, 0xdd, 0x70, 0x5e, 0xea, 0x74, 0x8f, 0xeb, 0xe9, 0x59, 0xd8, 0x7a,
	0x06, 0x76, 0x14, 0x35, 0x6c, 0x3d, 0xc3, 0x3a, 0xab, 0x85, 0xad, 0xe7, 0x49, 0xad, 0x7f, 0x0b,
	0x5b, 0xcf, 0x81, 0xa9, 0xa8, 0xf1, 0x1c, 0x24, 0x5f, 0x7c, 0xb8, 0x33, 0x2a, 0x4b, 0xc1, 0x2f,
	0xe8, 0xb7, 0xc4, 0x85, 0x2f, 0x1c, 0x8a, 0x78, 0x54, 0xcd, 0xd3, 0x99, 0xcf, 0x2d, 0x8a, 0xc3,
	0x65, 0x51, 0xac, 0x4d, 0xe2, 0xd2, 0xc5, 0xd3, 0x35, 0xba, 0x88, 0x21, 0xca, 0xaa, 0x44, 0x13,
	0xd3, 0xc7, 0x28, 0x6d, 0xb0, 0x8e, 0x5b, 0x39, 0xcd, 0x35, 0x71, 0xc9, 0x2b, 0xd8, 0xb9, 0x49,
	0xee, 0xcf, 0x37, 0x6b, 0xf0, 0xdd, 0x83, 0xe0, 0x9d, 0x24, 0x81, 0x47, 0xb0, 0x75, 0xed, 0x39,
	0x92, 0xc8, 0x1c, 0x4f, 0x94, 0x29, 0x3a, 0xbe, 0xb7, 0xf2, 0xf1, 0x4a, 0x36, 0xf4, 0xa6, 0xb6,
	0xfb, 0x84, 0x77, 0x97, 0x37, 0xac, 0xca, 0xc1, 0x56, 0xad, 0x5e, 0xb2, 0x81, 0xaf, 0x61, 0x7b,
	0xb1, 0x40, 0xbc, 0xbf, 0x66, 0x26, 0xf1, 0x03, 0xb7, 0xd3, 0xa6, 0x3b, 0xed, 0x9a, 0xff, 0xc6,
	0xf0, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x86, 0x95, 0xc5, 0x45, 0x06, 0x00, 0x00,
}
